apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: {{ .Values.ingress.paths.backend }}
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 80
      - path: {{ .Values.ingress.paths.frontend }}
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
